include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maintainability-index: 50
    maximum-nesting: 5
    number-of-parameters: 7
    source-lines-of-code: 100
  rules:
    - arguments-ordering:
        child-last: true
    - avoid-ignoring-return-values: false
    - newline-before-return: false
    - member-ordering:
        widgets-order:
          - build-method
    - prefer-static-class:
        ignore-annotations:
          - Riverpod
          - riverpod
    - prefer-trailing-comma:
        break-on: 3
    - prefer-correct-identifier-length:
        exceptions: [ 'id','i' ]
    - prefer-immediate-return: false
    - prefer-match-file-name: false
    - prefer-conditional-expressions: false
    - avoid-late-keyword: false
    - prefer-static-class: false
    - no-magic-number:
        allow-only-once: true
    - prefer-extracting-callbacks:
        allowed-line-count: 5
    - prefer-moving-to-variable:
        allowed-duplicated-chains: 3
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-passing-async-when-sync-expected: false
    - no-equal-arguments: false



linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    always_use_package_imports: true
    always_declare_return_types: true
    avoid_positional_boolean_parameters: true
    unawaited_futures: true
    use_key_in_widget_constructors: true


