include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    always_use_package_imports: true
    always_declare_return_types: true
    avoid_positional_boolean_parameters: true
    unawaited_futures: true
    use_key_in_widget_constructors: true