name: track_me
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Used for state management
  flutter_riverpod: ^2.3.6

  # Used for log
  logger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
   # a tool running code generators
  build_runner: ^2.3.3

  # Code generator for @riverpod annotation
  riverpod_generator: ^2.2.1

  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^1.3.1

  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.3.4

  # Used for json serialization
  json_serializable: ^6.6.1

  # Analyzer
  dart_code_metrics: ^5.7.2
  dart_code_metrics_presets: ^1.6.0


flutter:
  uses-material-design: true

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf

        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 600

        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 700

        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 900